# Dockerfile
FROM nginx:1.23

# Copy file cấu hình Nginx vào container
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy source từ Next.js (nếu build sẵn)
# COPY ../front-end/src/app /usr/share/nginx/html
